#!/bin/bash

: ${LOGFILE:=/tmp/plugn_file.log}
: ${DEBUG:=1}

main(){
  read key dest
  debug "key=$key dest=$dest"
  curl "http://127.0.0.1:8500/v1/kv/$key?raw" | base64 -d > $dest || debug "Couldn't get value from KV store."
}

debug(){
  [[ "$DEBUG" ]] && echo "[DEBUG] $*" >> $LOGFILE
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"