#!/bin/bash

: ${LOGFILE:=/tmp/plugn_gcp_p12.log}
: ${DEBUG:=1}

main(){
  debug "Getting p12 file from Consul's key-value store"
  curl "http://$CONSUL_HOST:$CONSUL_HTTP_PORT/v1/kv/recipes/gcp-p12/p12-encoded" | base64 -d > /usr/lib/hadoop/lib/gcp.p12
  debug "p12 file successfully downloaded from key-value store."
}

debug(){
  [[ "$DEBUG" ]] && echo "[DEBUG] $*" >> $LOGFILE
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"